export const SEARCH_CUSTOMERS_INIT = 'Form/SEARCH_CUSTOMERS_INIT';
export const SEARCH_CUSTOMERS_SUCCESS = 'Form/SEARCH_CUSTOMERS_SUCCESS';
export const SEARCH_CUSTOMERS_ERROR = 'Form/SEARCH_CUSTOMERS_ERROR';
export const SET_FORM_FIELD = 'Form/SET_FORM_FIELD';
export const SET_FORM_ERRORS = 'Form/SET_FORM_ERRORS';
